language: node_js
node_js: stable
install:
- yarn
script:
- yarn run clean
- yarn run build
after_script:
- cd ./public
- git init
- git config --global user.name "Mslxl"
- git config --global user.email "1302485739@qq.com"
- git add -A
- git commit -m "Travis CI Auto Builder"
- git push --force -u "https://mslxl:${REPO_TOKEN}@${GH_REF}" master
branches:
  only:
  - source
cache:
  apt: true
  directories:
  - node_modules
env:
  global:
  - GH_REF: e.coding.net/mslxl/mslxl.coding.me.git
  - secure: fGY4fHvzK6y5BOpkh1qjTwonBiZ4AdM8dKDWladQ7uuKj0AFLj04rpmqI9dQYTDzP1lXSIEfm7wGARgNpDHnHmFfRcIFvphIFJ2YQhPwXJolkoWBLUUUW67uW4vNLGIKaUBgY4N+020n8eyNtwCEiWP0R6I5JpdOVIXUwAsW4Ds/ohDsLOEszqSgwtzCilG92Q0yAHdK9p8ahRpt/dteueMi+c2eEZnmqp/76zmp0u0hfiPgC/u7xEO/q6+e+UuJ7RNSd2oQoUqJ4v9WsZntBoWhcigDLGohS2pFOxRgSw7nF1NAeLvDXXipENRTvNXBl+9sLZtvy4v/xHnyu2qTB/VzkMWPS6jGdE3dQwFj0hFBv1MVjiVHEt0xrNgXila6E/vMfTHJ1Yt76OYP7S4MNT0+jQzYu9yBTKj+kULN1w8mmc9RUriuXoRnhABcW3Egyjy1RoaJWwjZaxcFX2YVVxAuIaiTQJ//3Xisiog7IeHL9+0Zwb1UpZvdvBPDPhUx0BWk2hTzB7HU8mJymQxJsG0aX1kq4xm5CoH8hMGfuUUeu1GZ6JIVlOWfG3SXHpNUD94Xni0tn19MA4lcHSU8elpv//kxjcFJ3iSbZoPkWBwRoB+oWv02Gncv+SfjtwNBXxcoU1IdpgRT/GkHGtncRBy3/ihA4pGTK+QE5BjCtew=
