language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install
script:
- hexo clean
- hexo g
after_script:
- cd ./public
- git init
- git config --global user.name "Mslxl"
- git config --global user.email "1302485739@qq.com"
- git add -A
- git commit -m "Travis CI Auto Builder"
- git push --force -u "https://mslxl:${REPO_TOKEN}@${GH_REF}" master
branches:
  only:
  - master
env:
  global:
  - GH_REF: git.coding.net/mslxl/mslxl.coding.me
  - secure: q0wRe/Z8FigXgzrEj08rZglYYbR8JRQkZAxbqnrD49wlYXw5dLJfyCoM+uA43pKB6FiZWOvccAsB1M/E1icWrlCTceQLEu/q1pkFMA7OHEF9/VOE5ozCljyADTkz2qnnFds99trYweyUciLTxLvJvDf4ysDDs8yqnvGc9MhtRh+U7odgWQY04T9QBXk+DNKrr1yw1VHtTJV0D8KjeyHL9YF78kmBO32x/784a69Rt+s9VpjkssvqTBMM2DAxzVB8frJNHGs8iKsJdF4AomkPc2pucoyUicE+ZZdHwnqsKPxy+s3yJT0MmC8wKURFl4am6lW61qJutftc489MSfL5IQegTqrQD8I8+2875847J8UcWC/TAnDofYT6mCdlhBad30ruiefZqVJl0NN0acOupJlEEG4BX2qeHB2uUjfDTZEWIxS5TJXF5vYZZ5gKs+QKnvPzLRceI+2WRVLoijqB45mi42aB3s3owmGaJOw8uaT2n7DwIGzrYfY0sisVyKX7PReYEeJqR5OQwx2ldBgnDjO7mIPgyUfhL95HYxP99Pbew1A1mRoielzCmi1P5ntbBl2ULyqgQdynR5ietpxl4iNkTO+YnlwNCawwS5eVreji6yz7VuU12j2jdTqIPqtU9lExM5mOCTnEQ1DIedmwBjT7/wUmgEesxT+BGHOwt+0=
