title: Mslxl'Blog

username: mslxl
email: 1302485739@qq.com

description: > # this means to ignore newlines until "baseurl:"
  绝对没有一点技术含量
baseurl: ""
url: "http://mslxl.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate
  
paginate: 8

github_username:  mslxl


# SideNav
sidenav_enabel: true
sidenav_bg: "/img/sidebar_header.png"
avatar: "https://avatars3.githubusercontent.com/u/11132880?s=460"

